name: Build & Release
run-name: Build & Release
on: push

jobs:
  build:
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [arm64, amd64]
    runs-on: ${{ matrix.goos }}
    steps:
    - name: Check out smart-dns-updater
      uses: actions/checkout@v4
    - run: |
        bazelisk build //:smart-dns-updater_${{ matrix.goos }}_${{ matrix.goarch }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: smart-dns-updater_${{ matrix.goos }}_${{ matrix.goarch }}
        path: bazel-bin/smart-dns-updater_${{ matrix.goos }}_${{ matrix.goarch }}_/smart-dns-updater_${{ matrix.goos }}_${{ matrix.goarch }}
        if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        # Only release on tags
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bazel-bin/smart-dns-updater_*_/smart-dns-updater_*
