name: Test
run-name: Test
on:
  push:
  pull_request:
    paths:
      - "!README.md"
      - "!LICENSE"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out smart-dns-updater
        uses: actions/checkout@v4
      - name: Test //...
        run: |
          bazelisk test --stamp --workspace_status_command=$PWD/status.sh //...
